### ISSUE TITLE
Download?

### ISSUE THREAD

**Issue by JLTlp** [Freggy/tryjump#4]
Can you give me a Download?

Thanks

**Comment by freggy** [comment]
You can clone it an build it yourself. All dependencies can be found on my profile.

**Comment by JLTlp** [comment]
On witch Version is this Plugin

**Comment by freggy** [comment]
Its intended use is for 1.8.x

**Comment by JLTlp** [comment]
When I start the Server then, there is this log:
`[12:32:36] [Server thread/INFO]: Starting minecraft server version 1.8.8
[12:32:36] [Server thread/INFO]: Loading properties
[12:32:36] [Server thread/INFO]: Default game type: SURVIVAL
[12:32:37] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[12:32:37] [Server thread/INFO]: Debug logging is disabled
[12:32:37] [Server thread/INFO]: Server Ping Player Sample Count: 12
[12:32:37] [Server thread/INFO]: Using 4 threads for Netty based IO
[12:32:37] [Server thread/INFO]: Generating keypair
[12:32:37] [Server thread/INFO]: Starting Minecraft server on *:12
[12:32:37] [Server thread/INFO]: Using epoll channel type
[12:32:37] [Server thread/ERROR]: Could not load 'plugins/tryjump.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:154) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more`
